name: StadiumIQ CI-CD Workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Setup Node.js Env
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          npm install --no-save @rolldown/binding-linux-x64-gnu @rollup/rollup-linux-x64-gnu

      - name: Run Lint checks
        run: npm run lint

      - name: Run Test Suites
        run: npm run test

      - name: Run Compile & Builds Validation
        run: npm run build
